//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public EVENTO()
        {
            this.INSCRIPCION = new HashSet<INSCRIPCION>();
            this.OPCION_EVENTO = new HashSet<OPCION_EVENTO>();
            this.MOVIMIENTOS = new HashSet<MOVIMIENTOS>();
        }
    
        public decimal ID_EVENTO { get; set; }
        public string NOMBRE_EVENTO { get; set; }
        public string FECHA_INICIO { get; set; }
        public string FECHA_FIN { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ICollection<INSCRIPCION> INSCRIPCION { get; set; }
        public virtual ICollection<OPCION_EVENTO> OPCION_EVENTO { get; set; }
        public virtual ICollection<MOVIMIENTOS> MOVIMIENTOS { get; set; }
    }
}
