//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS
    {
        public decimal ID_MOVIMIENTO { get; set; }
        public Nullable<decimal> ID_PARTICIPANTE { get; set; }
        public Nullable<decimal> ID_EVENTO { get; set; }
        public string TIPO_MOV { get; set; }
        public Nullable<decimal> TIPO_PAGO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<System.DateTime> FECHA_MOVIMIENTO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
        public virtual PARTICIPANTE PARTICIPANTE { get; set; }
    }
}
