//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCION_EVENTO
    {
        public OPCION_EVENTO()
        {
            this.INSCRIPCION_OPCION = new HashSet<INSCRIPCION_OPCION>();
        }
    
        public decimal ID_OPCION { get; set; }
        public Nullable<decimal> ID_EVENTO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
        public virtual ICollection<INSCRIPCION_OPCION> INSCRIPCION_OPCION { get; set; }
    }
}
