//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTE
    {
        public PARTICIPANTE()
        {
            this.INSCRIPCION = new HashSet<INSCRIPCION>();
            this.PARTICIPANTE_CONTACTO = new HashSet<PARTICIPANTE_CONTACTO>();
            this.MOVIMIENTOS = new HashSet<MOVIMIENTOS>();
        }
    
        public decimal ID_PARTICIPANTE { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string GENERO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string ALERJICO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTADO_REGISTRO { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ICollection<INSCRIPCION> INSCRIPCION { get; set; }
        public virtual ICollection<PARTICIPANTE_CONTACTO> PARTICIPANTE_CONTACTO { get; set; }
        public virtual ICollection<MOVIMIENTOS> MOVIMIENTOS { get; set; }
    }
}
